### ISSUE TITLE
ResultManager should store results scoped per poll_id

### ISSUE THREAD

**Issue by smn** [praekelt/vxpolls#13]

**Comment by smn** [comment]
turned out to be a non-issue

**Comment by dmaclay** [comment]
The real problem is that we archive Participants but not Poll Results - this can lead to situations where, on a later pass through a poll, the is_suitable_question check gives false positives because it uses the old results.
The best solution is probably to use only the label values saved into Participant (which all user specified labels are) for the is_suitable_question check

**Comment by smn** [comment]
This has been resolved via a PR
